name: Aprendiendo-github-actions
run-name: ${{ github.actor }} esta aprendiendo GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
  notify:
    runs-on: ubuntu-latest
    needs: [check-bats-version]
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'GitHub Action Status'
          body: 'The GitHub Action was executed successfully.'
          to: 'desarrollador911@gmail.com'
